// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage(null, "ENC1003")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:ParTboT.Events.BotEvents.ClientReceivedVoice.TimeoutTimerElapsed(System.UInt64,System.Timers.ElapsedEventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:ParTboT.Events.BotEvents.ClientReceivedVoice.CommandsEngine_SpeechRecognized(System.UInt64,System.Speech.Recognition.SpeechRecognizedEventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:ParTboT.Events.BotEvents.ClientReceivedVoice.StartEngine_SpeechRecognized(System.UInt64,System.Speech.Recognition.SpeechRecognizedEventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:ParTboT.Events.BotEvents.SynthExtention.SpeakToVC(System.Speech.Synthesis.SpeechSynthesizer,DSharpPlus.VoiceNext.VoiceTransmitSink,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:ParTboT.Events.BotEvents.ClientReceivedVoice.VoiceReceiveHandler(DSharpPlus.VoiceNext.VoiceNextConnection,DSharpPlus.VoiceNext.EventArgs.VoiceReceiveEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:ParTboT.Events.BotEvents.ClientReceivedVoice.CommandsEngine_SpeechRecognized(DSharpPlus.Entities.DiscordUser,System.Speech.Recognition.SpeechRecognizedEventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:ParTboT.Events.BotEvents.ClientReceivedVoice.StartEngine_SpeechRecognized(DSharpPlus.Entities.DiscordUser,System.Speech.Recognition.SpeechRecognizedEventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~F:ParTboT.Events.BotEvents.ClientReceivedVoice.StartEngine")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~F:ParTboT.Events.BotEvents.ClientReceivedVoice.CommandsEngine")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~F:ParTboT.Events.BotEvents.ClientReceivedVoice.Speaker")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:ParTboT.Events.BotEvents.ClientReceivedVoice.LeaveVC(GogyBot_Alpha.Events.Bot.UserRecognitionData)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:ParTboT.Events.BotEvents.ClientReceivedVoice.RemoveUserFromDict(DSharpPlus.Entities.DiscordUser)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:ParTboT.Events.BotEvents.SynthExtention.SpeakToVC(System.Speech.Synthesis.SpeechSynthesizer,DSharpPlus.VoiceNext.VoiceNextConnection,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<Pending>", Scope = "member", Target = "~M:ParTboT.ServicesContainer.InitializeServicesAsync(DSharpPlus.DiscordClient,System.Boolean,System.Boolean,System.Boolean)~System.Threading.Tasks.Task{ParTboT.ServicesContainer}")]
